spring:
  datasource:
    url: # enter jdbc url
    username: # enter username
    password: # enter password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: # enter schema name
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: # enter mongodb uri
      database: # enter mongodb database name

springdoc:
  swagger-ui:
    path: /swagger-ui/match
  api-docs:
    path: /api-docs

predict-service:
  url: # enter ai prediction service url
notification-service:
  url: # enter notification service url

feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        loggerLevel: basic

server:
  port: 4567