spring:
  datasource:
    url: jdbc:postgresql://l2.eren.wtf:5432/gamebuddydb
    username: gamebuddy
    password: 3uT4}dpjK2PUk2#n
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: schmatch
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: mongodb://gamebuddy:hMRbRvpq2dzX1Eqt@ac-ffig6la-shard-00-00.8ymoclu.mongodb.net:27017,ac-ffig6la-shard-00-01.8ymoclu.mongodb.net:27017,ac-ffig6la-shard-00-02.8ymoclu.mongodb.net:27017/?ssl=true&replicaSet=atlas-wt795g-shard-0&authSource=admin&retryWrites=true&w=majority
      database: gamebuddy

springdoc:
  swagger-ui:
    path: /swagger-ui/match
  api-docs:
    path: /api-docs

predict-service:
  url: http://l2.eren.wtf:4566
notification-service:
  url: http://l2.eren.wtf:4564

feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        loggerLevel: basic

server:
  port: 4567